---
version: "2.1"
services:
  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    environment:
      - TZ=Pacific/Auckland
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    restart: unless-stopped

volumes:
  portainer_data: